# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_opcion_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='numOpc',
            field=models.IntegerField(default=0),
        ),
    ]
